vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        contact_image:
            uri_prefix: /contact_images
            upload_destination: '%kernel.project_dir%/public/images/contacts'
            namer: Vich\UploaderBundle\Naming\OrignameNamer


