services:

    ZakJakub\OswisAccommodationBundle\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        tags: [ { name: 'kernel.view'} ]
        arguments:
          ['@security.user_password_encoder.generic', '@doctrine.orm.entity_manager.abstract', '@swiftmailer.mailer.abstract', '@monolog.logger_prototype', '@twig', '@security.token_storage']
        public: true

    Zakjakub\OswisAccommodationBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    Zakjakub\OswisAccommodationBundle\Api\Dto\:
        resource: '../../Api/Dto/*'
        public: true

    Zakjakub\OswisAccommodationBundle\Api\EventSubscriber\:
        resource: '../../Api/EventSubscriber/*'
        public: true
