### OSWIS AddressBook - services

services:

    #    OswisOrg\OswisAddressBookBundle\EventSubscriber\:
    #        resource: '../../EventSubscriber/*'
    #        tags: [ { name: 'kernel.view'} ]
    #        arguments:
    #          ['@security.user_password_encoder.generic', '@doctrine.orm.entity_manager.abstract', '@swiftmailer.mailer.abstract', '@monolog.logger_prototype', '@twig', '@security.token_storage']
    #        public: true
    #
    #    OswisOrg\OswisAddressBookBundle\Controller\:
    #        resource: '../../Controller/*'
    #        tags: ['controller.service_arguments']
    #        public: true
    #
    #    OswisOrg\OswisAddressBookBundle\Api\Dto\:
    #        resource: '../../Api/Dto/*'
    #        public: true
    #
    #    OswisOrg\OswisAddressBookBundle\Api\EventSubscriber\:
    #        resource: '../../Api/EventSubscriber/*'
    #        public: true

    ### OSWIS AddressBook Settings Provider
    oswis_org_oswis_address_book.oswis_address_book_settings_provider:
        class: OswisOrg\OswisAddressBookBundle\Provider\OswisAddressBookSettingsProvider
        autowire: true
        public: true
    OswisOrg\OswisAddressBookBundle\Provider\OswisAddressBookSettingsProvider:
        alias: oswis_org_oswis_address_book.oswis_address_book_settings_provider
        public: true

    ### Place Service
    oswis_org_oswis_address_book.place_service:
        class: OswisOrg\OswisAddressBookBundle\Service\PlaceService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisAddressBookBundle\Service\PlaceService:
        alias: oswis_org_oswis_address_book.place_service
        public: true

    ### Person Service
    oswis_org_oswis_address_book.person_service:
        class: OswisOrg\OswisAddressBookBundle\Service\PersonService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisAddressBookBundle\Service\PersonService:
        alias: oswis_org_oswis_address_book.person_service
        public: true

    ### Organization Service
    oswis_org_oswis_address_book.organization_service:
        class: OswisOrg\OswisAddressBookBundle\Service\OrganizationService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisAddressBookBundle\Service\OrganizationService:
        alias: oswis_org_oswis_address_book.organization_service
        public: true

    ### AbstractContact Service
    oswis_org_oswis_address_book.abstract_contact_service:
        class: OswisOrg\OswisAddressBookBundle\Service\AbstractContactService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_address_book.contact_detail_type_service'
    OswisOrg\OswisAddressBookBundle\Service\AbstractContactService:
        alias: oswis_org_oswis_address_book.abstract_contact_service
        public: true

    ### AddressBook Service
    oswis_org_oswis_address_book.address_book_service:
        class: OswisOrg\OswisAddressBookBundle\Service\AddressBookService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisAddressBookBundle\Service\AddressBookService:
        alias: oswis_org_oswis_address_book.address_book_service
        public: true

    ### ContactDetailType Service
    oswis_org_oswis_address_book.contact_detail_type_service:
        class: OswisOrg\OswisAddressBookBundle\Service\ContactDetailTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisAddressBookBundle\Service\ContactDetailTypeService:
        alias: oswis_org_oswis_address_book.contact_detail_type_service
        public: true

    ###
    ###  REPOSITORIES
    ###

    oswis_org_oswis_address_book.address_book_repository:
        class: OswisOrg\OswisAddressBookBundle\Repository\AddressBookRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'
    OswisOrg\OswisAddressBookBundle\Repository\AddressBookRepository:
        alias: oswis_org_oswis_address_book.address_book_repository
        public: true

    oswis_org_oswis_address_book.contact_detail_category_repository:
        class: OswisOrg\OswisAddressBookBundle\Repository\ContactDetailCategoryRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'
    OswisOrg\OswisAddressBookBundle\Repository\ContactDetailCategoryRepository:
        alias: oswis_org_oswis_address_book.contact_detail_category_repository
        public: true

    oswis_org_oswis_address_book.organization_repository:
        class: OswisOrg\OswisAddressBookBundle\Repository\OrganizationRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'
    OswisOrg\OswisAddressBookBundle\Repository\OrganizationRepository:
        alias: oswis_org_oswis_address_book.organization_repository
        public: true

    oswis_org_oswis_address_book.person_repository:
        class: OswisOrg\OswisAddressBookBundle\Repository\PersonRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'
    OswisOrg\OswisAddressBookBundle\Repository\PersonRepository:
        alias: oswis_org_oswis_address_book.person_repository
        public: true

    oswis_org_oswis_address_book.position_repository:
        class: OswisOrg\OswisAddressBookBundle\Repository\PositionRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'
    OswisOrg\OswisAddressBookBundle\Repository\PositionRepository:
        alias: oswis_org_oswis_address_book.position_repository
        public: true


    ### Organization Controller
    oswis_org_oswis_address_book.organization_controller:
        class: OswisOrg\OswisAddressBookBundle\Controller\OrganizationController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_address_book.organization_service'
            - '@oswis_org_oswis_address_book.oswis_address_book_settings_provider'
    OswisOrg\OswisAddressBookBundle\Controller\OrganizationController:
        alias: oswis_org_oswis_address_book.organization_controller
        public: true


    ### AGE UTILS
    oswis_org_oswis_address_book.oswis_address_book_age_utils:
        class: OswisOrg\OswisAddressBookBundle\Utils\AgeUtils
        autowire: true
        public: true
    OswisOrg\OswisAddressBookBundle\Utils\AgeUtils:
        alias: oswis_org_oswis_address_book.oswis_address_book_age_utils
        public: true


    oswis_org_oswis_address_book.oswis_address_book_contact_person_updater:
        class: OswisOrg\OswisAddressBookBundle\EventListener\ContactPersonUpdater
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_address_book.position_repository'
            - '@oswis_org_oswis_address_book.organization_repository'
        tags:
            -   name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'OswisOrg\OswisAddressBookBundle\Entity\Position'
                lazy: true
