Zakjakub\OswisAccommodationBundle\Entity\Organization:
    attributes:
        id:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organization_get'
        name:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        shortName:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        description:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        note:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        createdDateTime:
            groups: ['accommodation_organization_get']
        updatedDateTime:
            groups: ['accommodation_organization_get']
        facilities:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        organizationCashDesks:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organization_get'
        temporaryCashDesks:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organization_get'
        identificationNumber:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        street:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        street2:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        postalCode:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        city:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        houseNumber:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        doorNumber:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organizations_post'
                - 'accommodation_organization_get'
                - 'accommodation_organization_put'
        fullAddress:
            groups:
                - 'accommodation_organizations_get'
                - 'accommodation_organization_get'

Zakjakub\OswisAccommodationBundle\Entity\Facility:
    id:
        groups:
            - 'accommodation_organizations_get'
            - 'accommodation_organizations_post'
            - 'accommodation_organization_get'
            - 'accommodation_organization_put'
    name:
        groups:
            - 'accommodation_organizations_get'
            - 'accommodation_organization_get'

Zakjakub\OswisAccommodationBundle\Entity\OrganizationCashDesk:
    id:
        groups:
            - 'accommodation_organizations_get'
            - 'accommodation_organization_get'
    name:
        groups:
            - 'accommodation_organizations_get'
            - 'accommodation_organization_get'

Zakjakub\OswisAccommodationBundle\Entity\TemporaryCashDesk:
    id:
        groups:
            - 'accommodation_organizations_get'
            - 'accommodation_organization_get'
    name:
        groups:
            - 'accommodation_organizations_get'
            - 'accommodation_organization_get'
