Zakjakub\OswisAccommodationBundle\Entity\Facility:
    attributes:
        id:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'
        name:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        shortName:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        description:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        manager:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        facilityManager:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        note:
            groups:
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        createdDateTime:
            groups: ['accommodation_facility_get']
        updatedDateTime:
            groups: ['accommodation_facility_get']
        rooms:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        numberOfRooms:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'
        organization:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        temporaryCashDesks:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'
        street:
            groups:
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        street2:
            groups:
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        postalCode:
            groups:
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        city:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        houseNumber:
            groups:
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        doorNumber:
            groups:
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        fullAddress:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'
        specialPeriods:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'

Zakjakub\OswisAccommodationBundle\Entity\Organization:
    attributes:
        id:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        name:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'
        identificationNumber:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'

Zakjakub\OswisAccommodationBundle\Entity\Room:
    attributes:
        id:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        name:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'

Zakjakub\OswisAccommodationBundle\Entity\AccommodationUser:
    attributes:
        id:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facilities_post'
                - 'accommodation_facility_get'
                - 'accommodation_facility_put'
        username:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'
        fullName:
            groups:
                - 'accommodation_facilities_get'
                - 'accommodation_facility_get'
