Zakjakub\OswisAccommodationBundle\Entity\RoomCategory:
    attributes:
        id:
            groups:
                - 'accommodation_room_categories_get'
                - 'accommodation_room_category_get'
        name:
            groups:
                - 'accommodation_room_categories_get'
                - 'accommodation_room_categories_post'
                - 'accommodation_room_category_get'
                - 'accommodation_room_category_put'
        shortName:
            groups:
                - 'accommodation_room_categories_get'
                - 'accommodation_room_categories_post'
                - 'accommodation_room_category_get'
                - 'accommodation_room_category_put'
        createdDateTime:
            groups:
                - 'accommodation_room_category_get'
        updatedDateTime:
            groups:
                - 'accommodation_room_category_get'
        description:
            groups:
                - 'accommodation_room_categories_get'
                - 'accommodation_room_categories_post'
                - 'accommodation_room_category_get'
                - 'accommodation_room_category_put'
        note:
            groups:
                - 'accommodation_room_categories_get'
                - 'accommodation_room_categories_post'
                - 'accommodation_room_category_get'
                - 'accommodation_room_category_put'
        numberOfRooms:
            groups:
                - 'accommodation_room_categories_get'
                - 'accommodation_room_category_get'
        rooms:
            groups:
                - 'accommodation_room_category_get'

Zakjakub\OswisAccommodationBundle\Entity\Room:
    attributes:
        id:
            groups:
                - 'accommodation_room_category_get'
        name:
            groups:
                - 'accommodation_room_category_get'

