Zakjakub\OswisAccommodationBundle\Entity\AccommodationUserCategory:
    attributes:
        id:
            groups: ['accommodation_user_categories_get', 'accommodation_user_category_get']
        name:
            groups:
                - 'accommodation_user_categories_get'
                - 'accommodation_user_categories_post'
                - 'accommodation_user_category_get'
                - 'accommodation_user_category_put'
        shortName:
            groups:
                - 'accommodation_user_categories_get'
                - 'accommodation_user_categories_post'
                - 'accommodation_user_category_get'
                - 'accommodation_user_category_put'
        createdDateTime:
            groups: ['accommodation_user_category_get']
        updatedDateTime:
            groups: ['accommodation_user_category_get']
        description:
            groups:
                - 'accommodation_user_categories_post'
                - 'accommodation_user_category_get'
                - 'accommodation_user_category_put'
        note:
            groups:
                - 'accommodation_user_categories_post'
                - 'accommodation_user_category_get'
                - 'accommodation_user_category_put'
        deleted:
            groups:
                - 'accommodation_user_categories_get'
                - 'accommodation_user_categories_post'
                - 'accommodation_user_category_get'
                - 'accommodation_user_category_put'
        startDateTime:
            groups:
                - 'accommodation_user_categories_get'
                - 'accommodation_user_categories_post'
                - 'accommodation_user_category_get'
                - 'accommodation_user_category_put'
        endDateTime:
            groups:
                - 'accommodation_user_categories_get'
                - 'accommodation_user_categories_post'
                - 'accommodation_user_category_get'
                - 'accommodation_user_category_put'
        accommodationUsers:
            groups:
                - 'accommodation_user_category_get'

Zakjakub\OswisAccommodationBundle\Entity\AccommodationUser:
    attributes:
        id:
            groups: ['accommodation_user_category_get']
        appUser:
            groups: ['accommodation_user_category_get']
#
#App\Entity\AppUser:
#    attributes:
#        id:
#            groups: ['accommodation_user_category_get']
#        username:
#            groups: ['accommodation_user_category_get']
#        fullName:
#            groups: ['accommodation_user_category_get']
#
#



