Zakjakub\OswisAccommodationBundle\Entity\MaintenancePeriod:
    attributes:
        id:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_period_get'
        name:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        shortName:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        createdDateTime:
            groups:
                - 'accommodation_maintenance_period_get'
        updatedDateTime:
            groups:
                - 'accommodation_maintenance_period_get'
        description:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        note:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        startDateTime:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        endDateTime:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        facilities:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        rooms:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        reason:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'
        accommodationNotAvailable:
            groups:
                - 'accommodation_maintenance_periods_get'
                - 'accommodation_maintenance_periods_post'
                - 'accommodation_maintenance_period_get'
                - 'accommodation_maintenance_period_put'

Zakjakub\OswisAccommodationBundle\Entity\Room:
    attributes:
        id:
            groups:
                - 'accommodation_maintenance_period_get'
        name:
            groups:
                - 'accommodation_maintenance_period_get'

Zakjakub\OswisAccommodationBundle\Entity\Facility:
    attributes:
        id:
            groups:
                - 'accommodation_maintenance_period_get'
        name:
            groups:
                - 'accommodation_maintenance_period_get'

