OswisOrg\OswisAddressBookBundle\Entity\Organization:
    attributes:
        shortName:
            groups:
                - 'address_book_organizations_get'
                - 'address_book_organizations_post'
                - 'address_book_organization_get'
                - 'address_book_organization_put'

        identificationNumber:
            groups:
                - 'address_book_organizations_get'
                - 'address_book_organizations_post'
                - 'address_book_organization_get'
                - 'address_book_organization_put'

        color:
            groups:
                - 'address_book_organizations_get'
                - 'address_book_organizations_post'
                - 'address_book_organization_get'
                - 'address_book_organization_put'

        parentOrganization:
            groups:
                - 'address_book_organizations_get'
                - 'address_book_organizations_post'
                - 'address_book_organization_get'
                - 'address_book_organization_put'




