OswisOrg\OswisAddressBookBundle\Entity\Person:
    attributes:
        birthDate:
            groups:
                - 'address_book_persons_get'
                - 'address_book_persons_post'
                - 'address_book_person_get'
                - 'address_book_person_put'
        age:
            groups:
                - 'address_book_person_get'

